name: Notify when pullrequest is commented

on: 
  issue_comment:
    types: [created]
  pull_request_review_comment:

jobs:
  notify:
    runs-on: paygo-yarn
    steps:
      - name: Slack Notification on pull_request comment
        if: ${{ github.event.issue.pull_request }}
        uses: rtCamp/action-slack-notify@v2.1.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: stream-repo-portal
          SLACK_COLOR: '#59656f'
          SLACK_TITLE: 'O pr #${{ github.event.issue.number }} foi atualizado'
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_USERNAME: Github Actions
          SLACK_MESSAGE: '${{ github.event.comment.user.login }} comentou no pr #${{ github.event.issue.number }}'
          SLACK_FOOTER: '${{ github.event.comment.html_url }}'

      - name: Slack Notification on pull_request review comment
        if: ${{ github.event.pull_request }}
        uses: rtCamp/action-slack-notify@v2.1.3
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: stream-repo-portal
          SLACK_COLOR: '#59656f'
          SLACK_TITLE: 'O pr #${{ github.event.pull_request.number }} foi atualizado'
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          SLACK_USERNAME: Github Actions
          SLACK_MESSAGE: '${{ github.event.comment.user.login }} comentou no pr #${{ github.event.pull_request.number }}'
          SLACK_FOOTER: '${{ github.event.comment.html_url }}'